"""Post-process saved task-level trajectories by inserting observation steps."""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
import json
from pathlib import Path
import shutil
from typing import Any, Sequence

from data_generation.task_level.tasks.shared.constants import (
    NAVIGATION_TOOL_NAMES,
    WAIT_TOOL_NAMES,
)
from data_generation.utils import stable_json_sha256, write_json_output
from tqdm import tqdm

TICK_ROWS_KEY = "tick_rows"
TICK_KEY = "tick"
GET_IMAGE_TOOL_NAME = "get_image"
LEGACY_ENV_IMAGE_TOOL_NAME = "get_env_image"
LEGACY_AGENT_IMAGE_TOOL_NAME = "get_agent_image"
COMMUNICATE_TOOL_NAME = "communicate"
TOP_VIEW_CAMERA = "top_view"
ROOM_VIEW_CAMERA = "room_view"
MAP_VIEW = "map"
WRIST_CAMERA = "wrist"
AGENT_VIEW_CENTER_CAMERA = "agentview_center"
AGENT_VIEW_LEFT_CAMERA = "agentview_left"
AGENT_VIEW_RIGHT_CAMERA = "agentview_right"
INITIAL_OBSERVATION_VIEWS = (
    TOP_VIEW_CAMERA,
    ROOM_VIEW_CAMERA,
    MAP_VIEW,
)
NAVIGATION_OBSERVATION_VIEWS = (
    AGENT_VIEW_CENTER_CAMERA,
    AGENT_VIEW_LEFT_CAMERA,
    AGENT_VIEW_RIGHT_CAMERA,
)
ACTION_OBSERVATION_VIEWS = (
    WRIST_CAMERA,
    AGENT_VIEW_CENTER_CAMERA,
)
LEGACY_INSERTED_OBSERVATION_TOOL_NAMES = frozenset(
    {
        GET_IMAGE_TOOL_NAME,
        LEGACY_ENV_IMAGE_TOOL_NAME,
        LEGACY_AGENT_IMAGE_TOOL_NAME,
    }
)
VIEW_REASONING_LABELS = {
    TOP_VIEW_CAMERA: "top-view",
    ROOM_VIEW_CAMERA: "room-view",
    MAP_VIEW: "map",
    WRIST_CAMERA: "wrist",
    AGENT_VIEW_CENTER_CAMERA: "center agent-view",
    AGENT_VIEW_LEFT_CAMERA: "left agent-view",
    AGENT_VIEW_RIGHT_CAMERA: "right agent-view",
}
ACTION_IMAGE_REASONING_TEMPLATES = {
    "before": (
        "I need {view_labels} images to observe the current scene before I "
        "execute {tool}."
    ),
    "after": (
        "I need {view_labels} images to observe the current scene after I "
        "executed {tool}."
    ),
}
POST_PROCESS_ERROR_EXIT_CODE = 1
POST_PROCESS_VALIDATION_ERROR_TYPE = "PostProcessingValidationRequired"
POST_PROCESS_VALIDATION_ERROR = (
    "Trajectory was post-processed after validation and must be revalidated."
)
RAW_DATASET_DIRECTORY_NAME = "raw"
PRE_IMAGE_DATASET_DIRECTORY_NAME = "pre_image"
IMAGE_DATASET_DIRECTORY_NAME = "image"
LEGACY_IMAGE_OUTPUT_DIRECTORY_NAME = "w_images"
POST_PROCESS_OUTPUT_DIRECTORY_NAMES = frozenset(
    {
        RAW_DATASET_DIRECTORY_NAME,
        PRE_IMAGE_DATASET_DIRECTORY_NAME,
        IMAGE_DATASET_DIRECTORY_NAME,
        LEGACY_IMAGE_OUTPUT_DIRECTORY_NAME,
    }
)


def build_step_image_path(
    trajectory_id: str,
    step_index: int,
    agent_id: str,
    view_name: str,
    *,
    tool_name: str = GET_IMAGE_TOOL_NAME,
) -> str:
    """Builds the deterministic relative image path for one inserted view."""

    # Keep the helper signature stable even though post-processing now emits
    # only the unified get_image layout.
    _ = tool_name
    filename = f"{step_index}_{view_name}_{agent_id}.png"
    return (Path("images") / trajectory_id / filename).as_posix()


def _build_step_image_paths(
    trajectory_id: str,
    step_index: int,
    agent_id: str,
    view_names: Sequence[str],
) -> list[str]:
    """Builds the ordered image paths for one multi-view get_image step."""

    return [
        build_step_image_path(
            trajectory_id,
            step_index,
            agent_id,
            view_name,
        )
        for view_name in view_names
    ]


def _copy_step_without_generated_fields(step: dict[str, Any]) -> dict[str, Any]:
    """Copies a persisted step while dropping fields regenerated by post-processing."""

    copied_step = dict(step)
    copied_step.pop("image_path", None)
    copied_step.pop("image_paths", None)
    return copied_step


def _format_view_labels(view_names: Sequence[str]) -> str:
    """Formats a stable human-readable label for one or more requested views."""

    formatted_labels: list[str] = []
    for view_name in view_names:
        view_label = VIEW_REASONING_LABELS.get(view_name)
        if view_label is None:
            raise ValueError(f"Unsupported get_image view: {view_name}")
        formatted_labels.append(view_label)

    if len(formatted_labels) == 1:
        return formatted_labels[0]
    if len(formatted_labels) == 2:
        return f"{formatted_labels[0]} and {formatted_labels[1]}"
    return ", ".join(formatted_labels[:-1]) + f", and {formatted_labels[-1]}"


def _build_action_get_image_reasoning(
    tool_name: str,
    *,
    timing: str,
    view_names: Sequence[str],
) -> str:
    """Builds direction-aware reasoning for one aggregated get_image step."""

    template = ACTION_IMAGE_REASONING_TEMPLATES.get(timing)
    if template is None:
        raise ValueError(f"Unsupported get_image timing: {timing}")
    return template.format(
        tool=tool_name,
        view_labels=_format_view_labels(view_names),
    )


def _build_get_image_step(
    agent_id: str,
    *,
    view_names: Sequence[str],
    reasoning: str,
) -> dict[str, Any]:
    """Builds one synthetic get_image step with a normalized views list."""

    return {
        "step": -1,
        "agent": agent_id,
        "tool": GET_IMAGE_TOOL_NAME,
        "args": {"views": list(view_names)},
        "reasoning": reasoning,
    }


def _build_initial_observation_step(agent_id: str) -> dict[str, Any]:
    """Builds the shared initial scene-inspection observation step."""

    return _build_get_image_step(
        agent_id,
        view_names=INITIAL_OBSERVATION_VIEWS,
        reasoning=(
            "I need top-view, room-view, and map images before the task begins."
        ),
    )


def _resolve_action_view_names(tool_name: str) -> tuple[str, ...]:
    """Chooses the inserted observation views for one wrapped action tool."""

    if tool_name in NAVIGATION_TOOL_NAMES:
        return NAVIGATION_OBSERVATION_VIEWS
    return ACTION_OBSERVATION_VIEWS


def _build_action_observation_step(
    agent_id: str,
    *,
    tool_name: str,
    timing: str,
) -> dict[str, Any]:
    """Builds one aggregated observation step around an action tool call."""

    view_names = _resolve_action_view_names(tool_name)
    return _build_get_image_step(
        agent_id,
        view_names=view_names,
        reasoning=_build_action_get_image_reasoning(
            tool_name,
            timing=timing,
            view_names=view_names,
        ),
    )


def _resolve_observation_step_view_names(step: dict[str, Any]) -> tuple[str, ...]:
    """Extracts the normalized ordered view names for one inserted get_image step."""

    args = step.get("args")
    if not isinstance(args, dict):
        raise ValueError("Inserted get_image steps must contain an args object.")

    view_names = args.get("views")
    if not isinstance(view_names, list) or not all(
        isinstance(view_name, str) for view_name in view_names
    ):
        raise ValueError(
            "Inserted get_image steps must contain args.views as a string list."
        )
    return tuple(view_names)


def rebuild_steps_with_image_observations(
    steps: list[dict[str, Any]],
    *,
    initial_image_agent_ids: Sequence[str],
    trajectory_id: str,
) -> list[dict[str, Any]]:
    """Rebuilds one step list with deterministic inserted observation steps."""

    cleaned_steps: list[dict[str, Any]] = []
    for step in steps:
        tool_name = step.get("tool")
        if tool_name in LEGACY_INSERTED_OBSERVATION_TOOL_NAMES:
            # Drop existing synthetic observation steps so reruns stay idempotent
            # and old split-tool outputs can be upgraded in one pass.
            continue

        cleaned_steps.append(_copy_step_without_generated_fields(step))

    # Keep the shared scene-inspection steps at the very front so each agent
    # captures the initial state before any coordination messages are emitted.
    rebuilt_steps: list[dict[str, Any]] = []
    rebuilt_steps.extend(
        _build_initial_observation_step(agent_id)
        for agent_id in initial_image_agent_ids
    )
    for copied_step in cleaned_steps:
        tool_name = copied_step.get("tool")
        if tool_name == COMMUNICATE_TOOL_NAME:
            rebuilt_steps.append(copied_step)
            continue

        agent_id = copied_step.get("agent")
        if not isinstance(agent_id, str) or not agent_id:
            raise ValueError(
                "Every non-communicate step must contain a non-empty agent."
            )

        rebuilt_steps.append(
            _build_action_observation_step(
                agent_id,
                tool_name=tool_name,
                timing="before",
            )
        )
        rebuilt_steps.append(copied_step)
        rebuilt_steps.append(
            _build_action_observation_step(
                agent_id,
                tool_name=tool_name,
                timing="after",
            )
        )

    # Renumber after insertion so saved step indices and image filenames stay
    # deterministic regardless of the input shape.
    for step_index, step in enumerate(rebuilt_steps):
        step["step"] = step_index
        if step["tool"] == GET_IMAGE_TOOL_NAME:
            view_names = _resolve_observation_step_view_names(step)
            step["image_paths"] = _build_step_image_paths(
                trajectory_id,
                step["step"],
                step["agent"],
                view_names,
            )
            step.pop("image_path", None)
            continue
        step.pop("image_path", None)
        step.pop("image_paths", None)
    return rebuilt_steps


def _tick_row_agent_ids(rows: Sequence[dict[str, Any]]) -> tuple[str, ...]:
    """Collects the agents appearing in tick rows, in first-seen order."""

    agent_ids: list[str] = []
    seen: set[str] = set()
    for row in rows:
        if not isinstance(row, dict):
            continue
        for key in row:
            if key != TICK_KEY:
                _append_unique_agent_id(agent_ids, seen, key)
    return tuple(agent_ids)


def rebuild_tick_rows_with_image_observations(
    rows: Sequence[dict[str, Any]],
    *,
    agent_ids: Sequence[str],
) -> list[dict[str, Any]]:
    """Rebuilds tick rows with observations, preserving the coordination schedule.

    The flat injector pads each agent's stream in proportion to its own action
    count, and `communicate` is never padded. Two agents therefore accumulate
    different amounts of padding and drift apart: a release can end up firing
    before its waiter has blocked, which is a deadlock the model never wrote.
    Dilating the grid instead -- one source tick becomes an observe row, the
    original row, and an observe-again row, with EVERY agent moving together --
    leaves simultaneity and every ask/wait/release ordering exactly as written.

    Waits are not bracketed: a blocked agent is not looking at anything, and
    the wait must stay immediately after its ask for `_check_ask` to pass.
    """

    dilated: list[dict[str, dict[str, Any]]] = [
        {agent_id: _build_initial_observation_step(agent_id) for agent_id in agent_ids}
    ]
    for row in rows:
        if not isinstance(row, dict):
            continue
        actions: dict[str, dict[str, Any]] = {}
        for agent_id in agent_ids:
            action = row.get(agent_id)
            if not isinstance(action, dict) or not action.get("tool"):
                continue
            if action["tool"] in LEGACY_INSERTED_OBSERVATION_TOOL_NAMES:
                # Keeps reruns idempotent, exactly as the flat path does.
                continue
            actions[agent_id] = _copy_step_without_generated_fields(action)
        if not actions:
            continue

        bracketed = {
            agent_id: action["tool"]
            for agent_id, action in actions.items()
            if action["tool"] != COMMUNICATE_TOOL_NAME
            and action["tool"] not in WAIT_TOOL_NAMES
        }
        # An empty observe row is dropped rather than kept as a blank instant.
        # That shortens the schedule for every agent by the same tick, so the
        # alignment the dilation exists to protect is unaffected.
        for timing in ("before", None, "after"):
            if timing is None:
                dilated.append(actions)
                continue
            if not bracketed:
                continue
            dilated.append(
                {
                    agent_id: _build_action_observation_step(
                        agent_id,
                        tool_name=tool_name,
                        timing=timing,
                    )
                    for agent_id, tool_name in bracketed.items()
                }
            )

    return [
        {TICK_KEY: tick_index, **{a: dict(act) for a, act in actions.items()}}
        for tick_index, actions in enumerate(dilated)
    ]


def _attach_tick_step_images(
    steps: list[dict[str, Any]],
    *,
    trajectory_id: str,
) -> None:
    """Fills in image paths on the flattened tick steps, in place."""

    for step in steps:
        step.pop("image_path", None)
        if step["tool"] != GET_IMAGE_TOOL_NAME:
            step.pop("image_paths", None)
            continue
        step["image_paths"] = _build_step_image_paths(
            trajectory_id,
            step["step"],
            step["agent"],
            _resolve_observation_step_view_names(step),
        )


def _append_unique_agent_id(
    agent_ids: list[str],
    seen_agent_ids: set[str],
    agent_id: Any,
) -> None:
    """Appends a non-empty agent ID once while preserving its discovery order."""

    if not isinstance(agent_id, str) or not agent_id or agent_id in seen_agent_ids:
        return
    seen_agent_ids.add(agent_id)
    agent_ids.append(agent_id)


def _resolve_initial_image_agent_ids(trajectory: dict[str, Any]) -> tuple[str, ...]:
    """Chooses which agents receive the opening shared-scene observations."""

    resolved_agent_ids: list[str] = []
    seen_agent_ids: set[str] = set()
    for agent in trajectory.get("agents", ()):
        _append_unique_agent_id(
            resolved_agent_ids,
            seen_agent_ids,
            agent.get("agent"),
        )

    for step in trajectory.get("steps", ()):
        if step.get("tool") in LEGACY_INSERTED_OBSERVATION_TOOL_NAMES:
            continue
        _append_unique_agent_id(
            resolved_agent_ids,
            seen_agent_ids,
            step.get("agent"),
        )

    if resolved_agent_ids:
        return tuple(resolved_agent_ids)

    raise ValueError("Trajectory records must contain at least one valid agent.")


def _normalized_signature_payload(trajectory: dict[str, Any]) -> dict[str, Any]:
    """Builds the stable signature payload used by validated saved trajectories."""

    return {
        "agents": sorted(
            trajectory.get("agents", ()),
            key=lambda agent: agent["agent"],
        ),
        "steps": sorted(
            trajectory.get("steps", ()),
            key=lambda step: step["step"],
        ),
    }


def _replace_validation_with_post_process_status(trajectory: dict[str, Any]) -> None:
    """Replaces stale validation metadata after post-processing rewrites the steps."""

    validation = trajectory.get("validation")
    if not isinstance(validation, dict):
        return
    trajectory["validation"] = {
        "is_valid": False,
        "checks": [],
        "final_state": None,
        "error_type": POST_PROCESS_VALIDATION_ERROR_TYPE,
        "error": POST_PROCESS_VALIDATION_ERROR,
        "step": None,
        "signature": stable_json_sha256(_normalized_signature_payload(trajectory)),
    }


def post_process_trajectory(
    trajectory: dict[str, Any],
) -> dict[str, Any]:
    """Returns one rewritten trajectory record with inserted observation steps."""

    if not isinstance(trajectory.get("steps"), list):
        raise ValueError("Trajectory records must contain a steps list.")
    trajectory_id = trajectory.get("trajectory_id")
    if not isinstance(trajectory_id, str) or not trajectory_id:
        raise ValueError("Trajectory records must contain a non-empty trajectory_id.")

    updated_trajectory = dict(trajectory)
    tick_rows = updated_trajectory.get(TICK_ROWS_KEY)
    if isinstance(tick_rows, list):
        # Tick output carries its own schedule, and the flat injector would
        # scramble it. Rebuild the rows and re-derive the flat list from them so
        # the two stay the same plan.
        from tick_format import to_steps

        agent_ids = _resolve_initial_image_agent_ids(updated_trajectory)
        row_agent_ids = _tick_row_agent_ids(tick_rows)
        ordered_agent_ids = tuple(agent_ids) + tuple(
            agent_id for agent_id in row_agent_ids if agent_id not in set(agent_ids)
        )
        rebuilt_rows = rebuild_tick_rows_with_image_observations(
            tick_rows,
            agent_ids=ordered_agent_ids,
        )
        updated_trajectory[TICK_ROWS_KEY] = rebuilt_rows
        updated_trajectory["steps"] = to_steps(rebuilt_rows, ordered_agent_ids)
        _attach_tick_step_images(
            updated_trajectory["steps"],
            trajectory_id=trajectory_id,
        )
    else:
        updated_trajectory["steps"] = rebuild_steps_with_image_observations(
            updated_trajectory["steps"],
            initial_image_agent_ids=_resolve_initial_image_agent_ids(
                updated_trajectory
            ),
            trajectory_id=trajectory_id,
        )
    _replace_validation_with_post_process_status(updated_trajectory)
    return updated_trajectory


def _load_json_file(path: Path) -> dict[str, Any]:
    """Loads one JSON file and validates that the top-level payload is an object."""

    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"{path} must contain a top-level JSON object.")
    return payload


def resolve_output_dataset_path(dataset_path: Path) -> Path:
    """Maps one source dataset path to the default copied pre-image destination."""

    resolved_path = dataset_path.resolve()
    parts = list(resolved_path.parts)
    try:
        data_index = parts.index("data")
    except ValueError:
        return (
            dataset_path.parent / PRE_IMAGE_DATASET_DIRECTORY_NAME / dataset_path.name
        )

    relative_parts = parts[data_index + 1 :]
    if not relative_parts:
        return (
            dataset_path.parent / PRE_IMAGE_DATASET_DIRECTORY_NAME / dataset_path.name
        )

    if (
        len(relative_parts) >= 2
        and relative_parts[0] in POST_PROCESS_OUTPUT_DIRECTORY_NAMES
    ):
        return (
            Path(*parts[: data_index + 1])
            / PRE_IMAGE_DATASET_DIRECTORY_NAME
            / relative_parts[1]
            / Path(*relative_parts[2:])
        )
    if (
        len(relative_parts) >= 2
        and relative_parts[1] in POST_PROCESS_OUTPUT_DIRECTORY_NAMES
    ):
        return (
            Path(*parts[: data_index + 1])
            / PRE_IMAGE_DATASET_DIRECTORY_NAME
            / relative_parts[0]
            / Path(*relative_parts[2:])
        )
    return (
        Path(*parts[: data_index + 1])
        / PRE_IMAGE_DATASET_DIRECTORY_NAME
        / Path(*relative_parts)
    )


def _resolve_output_image_dir(output_dataset_path: Path) -> Path:
    """Resolves the sibling image directory referenced by inserted image steps."""

    return output_dataset_path.parent / "images"


def _resolve_summary_trajectory_paths(
    dataset_path: Path, payload: dict[str, Any]
) -> list[Path]:
    """Resolves trajectory file paths referenced by a summary dataset JSON."""

    trajectory_files = payload.get("trajectory_files")
    if not isinstance(trajectory_files, list):
        raise ValueError(
            "Summary datasets must contain a trajectory_files list of relative JSON paths."
        )

    resolved_paths: list[Path] = []
    for entry in trajectory_files:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            raise ValueError("Each trajectory_files entry must contain a string path.")
        resolved_paths.append((dataset_path.parent / entry["path"]).resolve())
    return resolved_paths


def _resolve_summary_trajectory_path_pairs(
    source_dataset_path: Path,
    output_dataset_path: Path,
    payload: dict[str, Any],
) -> list[tuple[Path, Path]]:
    """Resolves one source/output path pair per summary trajectory entry."""

    trajectory_files = payload.get("trajectory_files")
    if not isinstance(trajectory_files, list):
        raise ValueError(
            "Summary datasets must contain a trajectory_files list of relative JSON paths."
        )

    resolved_pairs: list[tuple[Path, Path]] = []
    for entry in trajectory_files:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            raise ValueError("Each trajectory_files entry must contain a string path.")
        relative_path = Path(entry["path"])
        resolved_pairs.append(
            (
                (source_dataset_path.parent / relative_path).resolve(),
                (output_dataset_path.parent / relative_path).resolve(),
            )
        )
    return resolved_pairs


def _materialize_summary_output_metadata(
    source_dataset_path: Path,
    output_dataset_path: Path,
) -> None:
    """Copies lightweight top-level metadata files into the output task directory."""

    source_root = source_dataset_path.parent
    output_root = output_dataset_path.parent
    if output_root.resolve() == source_root.resolve():
        return

    output_root.mkdir(parents=True, exist_ok=True)
    for source_path in source_root.iterdir():
        if not source_path.is_file():
            continue
        if source_path.name == source_dataset_path.name:
            continue
        shutil.copy2(source_path, output_root / source_path.name)


def _create_post_process_progress(*, total: int, disable_progress: bool) -> Any:
    """Creates the lightweight overall progress bar used during post-processing."""

    return tqdm(
        total=total,
        desc="Trajectories",
        disable=disable_progress,
        dynamic_ncols=True,
    )


def _set_post_process_progress_status(progress_bar: Any, status: str) -> None:
    """Updates the visible post-processing status text when progress is enabled."""

    if progress_bar is None or getattr(progress_bar, "disable", False):
        return
    progress_bar.set_postfix_str(status)
    progress_bar.refresh()


def _post_process_summary_trajectory_file(
    source_trajectory_path: Path,
    output_trajectory_path: Path,
) -> int:
    """Rewrites one saved trajectory file and returns its final step count."""

    trajectory = _load_json_file(source_trajectory_path)
    updated_trajectory = post_process_trajectory(trajectory)
    write_json_output(updated_trajectory, output_trajectory_path)
    return len(updated_trajectory["steps"])


def _post_process_payload_trajectory(
    index: int,
    trajectory: dict[str, Any],
) -> tuple[int, dict[str, Any]]:
    """Processes one inline trajectory while preserving caller-managed ordering."""

    return index, post_process_trajectory(trajectory)


def _post_process_summary_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
    workers: int,
) -> int:
    """Writes a copied summary dataset tree and post-processes its trajectories."""

    trajectory_count = len(_resolve_summary_trajectory_paths(dataset_path, payload))
    progress_bar = _create_post_process_progress(
        total=trajectory_count,
        disable_progress=disable_progress,
    )
    try:
        if output_dataset_path.parent.resolve() != dataset_path.parent.resolve():
            _set_post_process_progress_status(
                progress_bar,
                "copying summary metadata",
            )
            _materialize_summary_output_metadata(
                dataset_path,
                output_dataset_path,
            )

        # Post-processing only inserts deterministic image references, but later
        # rendering stages expect the sibling image root to exist up front.
        _resolve_output_image_dir(output_dataset_path).mkdir(
            parents=True, exist_ok=True
        )
        trajectory_path_pairs = _resolve_summary_trajectory_path_pairs(
            dataset_path,
            output_dataset_path,
            payload,
        )
        _set_post_process_progress_status(progress_bar, "rewriting trajectories")
        max_workers = min(workers, len(trajectory_path_pairs))
        if max_workers <= 1:
            for source_path, output_path in trajectory_path_pairs:
                _post_process_summary_trajectory_file(source_path, output_path)
                progress_bar.update(1)
        else:
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = [
                    executor.submit(
                        _post_process_summary_trajectory_file,
                        source_path,
                        output_path,
                    )
                    for source_path, output_path in trajectory_path_pairs
                ]
                for future in as_completed(futures):
                    future.result()
                    progress_bar.update(1)
        _set_post_process_progress_status(progress_bar, "writing summary")
        write_json_output(payload, output_dataset_path)
    finally:
        progress_bar.close()
    return trajectory_count


def _post_process_payload_dataset(
    dataset_path: Path,
    payload: dict[str, Any],
    *,
    output_dataset_path: Path,
    disable_progress: bool,
    workers: int,
) -> int:
    """Writes a copied inline dataset payload with post-processed trajectories."""

    trajectories = payload.get("trajectories")
    if not isinstance(trajectories, list):
        raise ValueError(
            "Inline datasets must contain a trajectories list or trajectory_files list."
        )

    progress_bar = _create_post_process_progress(
        total=len(trajectories),
        disable_progress=disable_progress,
    )
    try:
        # Keep inline-dataset outputs aligned with the summary-dataset layout so
        # downstream image rendering can use the same sibling image directory.
        _resolve_output_image_dir(output_dataset_path).mkdir(
            parents=True, exist_ok=True
        )
        _set_post_process_progress_status(progress_bar, "rewriting trajectories")
        max_workers = min(workers, len(trajectories))
        if max_workers <= 1:
            updated_trajectories = []
            for trajectory in trajectories:
                updated_trajectories.append(post_process_trajectory(trajectory))
                progress_bar.update(1)
        else:
            updated_trajectories = [None] * len(trajectories)
            with ThreadPoolExecutor(max_workers=max_workers) as executor:
                futures = [
                    executor.submit(_post_process_payload_trajectory, index, trajectory)
                    for index, trajectory in enumerate(trajectories)
                ]
                for future in as_completed(futures):
                    index, updated_trajectory = future.result()
                    updated_trajectories[index] = updated_trajectory
                    progress_bar.update(1)
        payload["trajectories"] = updated_trajectories
        _set_post_process_progress_status(progress_bar, "writing summary")
        write_json_output(payload, output_dataset_path)
    finally:
        progress_bar.close()
    return len(trajectories)


def post_process_dataset(
    dataset_path: Path,
    *,
    output_dataset_path: Path | None = None,
    disable_progress: bool = False,
    workers: int = 1,
) -> int:
    """Post-processes one dataset into a copied output JSON and returns the count."""

    if workers <= 0:
        raise ValueError("--workers must be greater than 0.")
    output_dataset_path = output_dataset_path or resolve_output_dataset_path(
        dataset_path
    )
    payload = _load_json_file(dataset_path)
    if "trajectory_files" in payload:
        return _post_process_summary_dataset(
            dataset_path,
            payload,
            output_dataset_path=output_dataset_path,
            disable_progress=disable_progress,
            workers=workers,
        )
    return _post_process_payload_dataset(
        dataset_path,
        payload,
        output_dataset_path=output_dataset_path,
        disable_progress=disable_progress,
        workers=workers,
    )
