"""Execution helpers for ``SimToolExecutor``."""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import imageio

_SWEEP_VERBOSE_ENV_VAR = "ROBOCASA_SWEEP_VERBOSE"


def _sim_tool_debug_enabled() -> bool:
    value = os.environ.get(_SWEEP_VERBOSE_ENV_VAR, "")
    return value.strip().lower() in {"1", "true", "yes", "on", "debug"}


class SimToolExecutorExecutionMixin:
    def run_tool_plan(
        self,
        tool_calls: list[dict[str, Any]],
        output_dir: str | Path,
        fps: int = 2,
        skip_videos: bool = False,
    ) -> dict[str, Any]:
        """
        Execute a list of tool calls, letting ``get_image`` steps produce images.

        Images are saved only when the plan contains ``get_image`` tool calls
        with ``image_paths``. When ``skip_videos`` is False, per-camera MP4
        videos are also generated by rendering all cameras before and after
        every action step.
        """
        tool_calls = self.ground_plan_template(tool_calls)
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        if skip_videos:
            scene_cameras = self.get_scene_description().get("cameras")
            if isinstance(scene_cameras, list) and scene_cameras:
                camera_names = [str(camera_name) for camera_name in scene_cameras]
            else:
                camera_names = list(getattr(self.runner, "camera_names", ()))
            if not camera_names:
                camera_names = list(self.render().keys())
        else:
            camera_names = list(self.render().keys())

        writers: dict[str, Any] = {}
        if not skip_videos:
            writers = {
                cam: imageio.get_writer(str(output_dir / f"{cam}.mp4"), fps=fps)
                for cam in camera_names
            }

        def _write_video_frame():
            if writers:
                frames = self.render()
                for cam, image in frames.items():
                    if cam in writers:
                        writers[cam].append_data(image)

        metadata = {
            "task": self.get_scene_description().get("task"),
            "steps": [],
            "cameras": camera_names,
        }

        try:
            _write_video_frame()

            for step_idx, tool_call in enumerate(tool_calls):
                tool_name = tool_call["tool"]
                robot_idx = tool_call.get("robot_idx", 0)
                args = tool_call.get("args", {})

                if _sim_tool_debug_enabled():
                    print(
                        f"[run_tool_plan] step {step_idx + 1}/{len(tool_calls)} "
                        f"robot={robot_idx} tool={tool_name} args={json.dumps(args, sort_keys=True)}"
                    )

                is_action = tool_name != "get_image"
                if is_action:
                    _write_video_frame()

                result = self.execute(tool_name, robot_idx=robot_idx, **args)

                if is_action:
                    _write_video_frame()

                robot_positions = {}
                for ri in range(self.runner._num_robots):
                    rp = self.runner._get_robot_position(ri)
                    robot_positions[f"robot{ri}"] = [
                        round(float(rp[0]), 3),
                        round(float(rp[1]), 3),
                        round(float(rp[2]), 3),
                    ]

                step_meta = {
                    "step_index": step_idx,
                    "tool": tool_name,
                    "robot_idx": robot_idx,
                    "args": args,
                    "success": result.success,
                    "details": result.details,
                    "robot_positions": robot_positions,
                }
                # `step_index` is the position in the EXECUTED plan, which stops
                # matching the position in the stored trajectory once the caller
                # runs the steps in concurrent-executor order. Carry the source
                # step through so a downstream join still lands on the right one.
                source_step = (tool_call.get("metadata") or {}).get("step_index")
                if source_step is not None:
                    step_meta["source_step_index"] = source_step
                if result.details.get("image_paths"):
                    step_meta["image_paths"] = result.details["image_paths"]

                metadata["steps"].append(step_meta)
                if _sim_tool_debug_enabled():
                    print(
                        f"[run_tool_plan] step {step_idx + 1}/{len(tool_calls)} "
                        f"success={result.success}"
                    )
        finally:
            for writer in writers.values():
                writer.close()

        with open(output_dir / "plan.json", "w") as f:
            json.dump(tool_calls, f, indent=2)
        with open(output_dir / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

        return metadata
